### PR TITLE
Feature/add programs fixes

### PR DESCRIPTION
**Pull request by ChaseBianchi**
image

[Trello card](https://trello.com/c/Kne7bDUc/50-as-a-cd-admin-i-can-add-programs)

- Upon navigating to Programs page, programs are fetched from back end, and stored in Context state, which can be used anywhere in the app after that. 
- I have wrapped the whole App in the ProgramsContext for now, but we can wrap specific components in it if that's overkill.
- The antd table then populates from the programs in state to fill the table with all the programs.
- It's a large table, and at some point we may want to only fetch/display programs for the club that the logged in CD/Admin is 'assigned' to.
- The component  that pops up when clicking 'add programs' is still **not** functional, but this was getting big, and I want to merge this before it gets too large.

### CODE REVIEW

**Review by pak11273 — APPROVED** [review]
looks good.

**Comment by ChaseBianchi** [comment]
@pak11273 I decided to create a separate Context from your user one.  Didn't want to complicate yours.  We can merge them at a later time if they both end up wrapping the whole app.

**Comment by pak11273** [comment]
I think it's fine the way it's separated out.  I think we could even handle 3 to 4 more context providers like this (members, activities ... )  It's far from unmanageable imo.

**Comment by ChaseBianchi** [comment]
Sounds good, I'm going to go ahead and merge then.

**Pull request merged**
