### PR TITLE
Feature/validate team member before scanner submission

### PR DESCRIPTION
**Pull request by pak11273**
# What's here (& what to consider)
* Validates the member before scan 

# Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality) 
- [ ] This change requires a documentation update

# Change Status

- [ ] Complete, tested, ready to review, and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete / work-in-progress, PR is for discussion or feedback
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

- [ ] Tested locally
- [ ] Test suite provides the same results as prior to making changes

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code# What's here (& what to consider)
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by JulsIII — DISMISSED** [review]

**Comment by pak11273** [comment]
I have something to fix on here.  Please do not merge yet until I resolve.  Thanks!

**Comment by pak11273** [comment]
Some breaking changes.  

- Reworked the member context api.  This now supports multiple properties.  We could consolidate future contexts to one provider and/or refactor existing ones.
- QR scanner now touches backend and checks member existence for both the scanner and manual input\
- Added some styling to error text.  ( I think the 'hasn't been scanned yet' line could be removed )
- Removed console.logs

**Review by maustrauk — APPROVED** [review]
Looks good

**Review by abc1929 — APPROVED** [review]
Should be good!

**Review by JulsIII — CHANGES_REQUESTED** [review]
Need to discuss this with you, you're making changes to stuff im using to get my logic to work (although its not fully working yet).

**Comment by pak11273** [comment]
Robert has these changes included but we are going his PR.

**Pull request closed without merging**
