### PR TITLE
adds spinner to loading component and adds loadingComponent to homeContainer

### PR DESCRIPTION
**Pull request by pak11273**
When redirecting from the Home Container you will see this animation instead of the admin dashboard

Animation

### CODE REVIEW

**Review by abc1929 — APPROVED** [review]
Looks fine to me

**Comment by pak11273** [comment]
I added these new changes because the loading component needed to be centered on screen.  In order for that to happen I created a wrapper component called 'LayoutContainer'.  Since this is a good pattern for page layout I wrapped all pages with it.  This makes it easy to have pages use a consistent design and makes centering easier because it uses flexbox.

**Review by abc1929 — COMMENTED** [review]
I think even though this would work now, it can be dangerous in the long run to add nested component where there might be alternative solutions. This PR needs approval from other team members working on the frontend. Currently, the components layers look like:
Screenshot from 2021-05-16 00-44-15

**Comment by pak11273** [comment]
Nothing really dangerous about it.  Layout containers are a common pattern in the React apps.  [Here ](https://auth0.com/blog/next-js-practical-introduction-for-react-developers-part-1/)is a similar approach but it locks the navbar in the layout which can limit design (eg. having loading component show by itself).  I'll bring this up in our next standup.

**Review by JulsIII — APPROVED** [review]

**Pull request merged**
